version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  assignees:
  - greaka
  ignore:
  - dependency-name: reqwest
    versions:
    - 0.11.0
    - 0.11.1
    - 0.11.2
